name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      shell: bash
      run: |
        pwd
        ls
        sudo ./build
    - name: run
      shell: bash
      run: |
        pwd
        ls
        ./bin/testcmake

