name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - shell: bash
      run: |
        cd bin/ 
        pwd
        ls
    - name: cmake
      shell: bash
      run: |
        cmake
    - name: make clean
      shell: bash
      run: |
        make clean
    - name: make 
      shell: bash
      run: |
        make 
    - name: run
      shell: bash
      run: |
        ./testcmake

