name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - shell: bash
      run: |
        cd bin/ 
        pwd
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
