name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - shell: bash
      run: |
        cd bin/ 
        pwd
        ls
    - name: make
      shell: bash
      run: |
        cd bin/
        make
    - name: make check
      shell: bash
      run: |
        cd /bin
        make check
    - name: make distcheck
      shell: bash
      run: |
        cd /bin
        make distcheck
